name: flutter_profile
description: Flutter profile package
version: 1.2.0
repository: https://github.com/Iconica-Development/flutter_profile

publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0

  flutter_input_library:
    git:
      url: https://github.com/Iconica-Development/flutter_input_library
      ref: 2.7.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
