name: flutter_profile
description: Flutter profile package
version: 1.0.1
repository: https://github.com/Iconica-Development/flutter_profile

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
