name: flutter_profile
description: Flutter profile package
version: 1.5.2
repository: https://github.com/Iconica-Development/flutter_profile
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0

  flutter_input_library:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^3.3.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
